global:
  scrape_interval: 5s # Alta resolución para entornos de desarrollo/pruebas

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3000']

  - job_name: 'chat-service'
    static_configs:
      - targets: ['chat-service:3001']